version: "3"
services:
  web:
    build:
      context: .
    depends_on:
      - postgres
    environment:
      env_file:
        ./dev.env
    ports:
      - "9001:9001"
    restart: always
    networks:
      - awesome
  postgres:
    image: postgres:12
    ports:
      - "5432:5432"
    volumes:
      - ./postgresdata:/var/lib/postgresql/data
    restart: always
    environment:
      env_file:
        ./dev.env
    networks:
      - awesome

networks:
    awesome:
        driver: bridge