version: "3"
services:
  web:
    build:
      context: .
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://postgres:newPassword@postgres:5432/redgreen
    ports:
      - "9001:9001"
    restart: always
    networks:
      - awesome
  postgres:
    image: postgres:12
    ports:
      - "5432:5432"
    volumes:
      - ./postgresdata:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: newPassword
      POSTGRES_DB: redgreen
    networks:
      - awesome

volumes:
    pgadmin-data:

networks:
    awesome:
        driver: bridge